config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'urls#index'

  resources :urls, only: %i[index create show], param: :url do
    member do
      get :info
    end
  end
  post ':short_url', to: 'urls#visit', as: :visit
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/click.rb
# == Schema Information
#
# Table name: clicks
#
#  id         :bigint           not null, primary key
#  url_id     :bigint
#  ip         :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Click < ApplicationRecord
  belongs_to :url, counter_cache: true
end

app/models/url.rb
# == Schema Information
#
# Table name: urls
#
#  id           :bigint           not null, primary key
#  short_url    :string           not null
#  initial_url  :string           not null
#  clicks_count :integer          default(0)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Url < ApplicationRecord
  MAX_LENGTH = 6
  validates :short_url, :initial_url, uniqueness: true
  validates :short_url, length: { maximum: MAX_LENGTH }
  validate :is_valid_url
  before_save :create_short_url
  has_many :clicks

  private

  def create_short_url
    self.short_url = (0...MAX_LENGTH).map{('A'..'Z').to_a[rand(26)]}.join
  end

  def is_valid_url
    uri =  URI.parse(self.initial_url)
    unless uri.is_a?(URI::HTTP) && !uri.host.nil?
      errors.add(:initial_url, "INVALID URL")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
# frozen_string_literal: true
require "uri"
class UrlsController < ApplicationController
  def index
    @urls = Url.all
    @url = Url.new
  end

  def create
    @url=Url.create(url_params)
    if @url.save
      redirect_to root_path
    else
      @urls = Url.all
      render :index
    end
  end

  def visit

    @url=Url.where(short_url:params["short_url"]).first
    if @url.present?
      @click=Click.new(url: @url, ip: request.remote_ip)
      @click.save
      uri = URI.parse(@url.initial_url)
      if uri.is_a?(URI::HTTP) && !uri.host.nil?
        redirect_to @url.initial_url, status: 302
      end
    end
  end

  def info
    @url=Url.includes(:clicks).find(params[:url])

  end

  private
  def url_params
    params.require(:url).permit(:initial_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clicks/_click.html.erb
<a href="#" class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
  <img src="https://github.com/twbs.png" alt="twbs" width="32" height="32" class="rounded-circle flex-shrink-0">
  <div class="d-flex gap-2 w-100 justify-content-between">
    <div>
      <h6 class="mb-0">IP <%= click.ip %></h6>
      <p class="mb-0 opacity-75">Created at <%= click.created_at %></p>
      <p class="mb-0 opacity-75">ID <%= click.id %></p>
    </div>
  </div>
</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tinyurl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
    <div class="row">
      <%= yield %>
    </div>
    </div>

  </body>
</html>

app/views/urls/_url.html.erb
<tr>
  <td scope="row"><%= link_to "http://127.0.0.1:3000/"+url.short_url, visit_path(url.short_url), method: :post %></td>
  <td><%= url.initial_url %> </td>
  <td><%= url.created_at %></td>
  <td><%= url.clicks_count %></td>
  <td><%= link_to 'INFO', info_url_path(url) %> </td>
</tr>

app/views/urls/index.html.erb
<% if flash[:notice] %>
  <div class="card-panel notice deep-orange"><%= flash[:notice] %></div>
<% end %>
<% @url.errors.full_messages.each do |msg| %>
  <li><%= msg  %></li>
<% end %>
<div class="row">
  <div class="col m12">
    <%= form_for @url do |f| %>
      <div class="card">
        <div class="card-content">
          <div class="row">
            <div class="col m8 offset-m2 center-align">
              <span class="card-title">Create a new short URL</span>
            </div>
          </div>
          <div class="row">
            <div class="col m6 offset-m2">
              <%= f.text_field :initial_url, class: 'validate form-control', placeholder: 'put the URL' %>
            </div>
            <div class="col m2">
              <button type="submit" class="btn btn-info">Create SHORT URL</button>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<table class="table highlight">
  <thead>
    <tr>
      <th scope="col">Short URL</th>
      <th scope="col">Initial URL</th>
      <th scope="col">Created</th>
      <th scope="col">Clicks Count</th>
      <th scope="col">Info</th>
    </tr>
  </thead>
  <tbody>
    <%= render @urls %>
  </tbody>
</table>

app/views/urls/info.html.erb
<div class="row">
        <div class="col-xl-8">
          <h1 class="bd-title mt-0">URL <%= @url.initial_url %></h1>
          <p class="bd-lead">Total CLICKS <%= @url.clicks_count %></p>

        </div>
        <div class="col-xl-4 d-lg-flex justify-content-xl-end">
          <%= link_to 'Back', root_path %>

        </div>
      </div>
<div class="list-group">
<%= render @url.clicks %>

</div>